# Site settings
title: ll-restaurant
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  vui vẻ, không qoại
baseurl: "/Ion-Jekyll-Theme" # the subpath of your site, e.g. /blog/
url: "http://ll-restaurant.github.io" # the base hostname & protocol for your site
twitter_username: llrestaurant
github_username:  llrestaurant

# Build settings
markdown: kramdown
